## Import the packages:

In [2]:
import requests
import pandas as pd 
from datetime import datetime
import os
import numpy as np
import pycountry_convert as pc

In [3]:
import sys 
print(sys.executable)

d:\DS Course\Earthquake_P1\.venv\Scripts\python.exe

## Endpoint URL:

In [4]:
url = "https://earthquake.usgs.gov/fdsnws/event/1/query"

## Record storeage:

In [5]:
all_records=[]
start_year=datetime.now().year -5
end_year=datetime.now().year
print(end_year)

2026

## Get year & month & Data record:

In [7]:
all_records = []

for year in range(start_year, end_year + 1):

    for month in range(1, 13):

        start_date = f"{year}-{month:02d}-01"

        if month == 12:
            end_date = f"{year + 1}-01-01"
        else:
            end_date = f"{year}-{month + 1:02d}-01"

        print("Extracting:", start_date, "→", end_date)

        params = {
            "format": "geojson",
            "starttime": start_date,
            "endtime": end_date,
            "minmagnitude": 3
        }

        # Call USGS API
        response = requests.get(url, params=params)

        # Check whether request was successful
        if response.status_code == 200:

            data = response.json()

            # Extract earthquake features
            features = data["features"]

            print("Earthquakes found:", len(features))

            # Convert each earthquake into dictionary
            for feature in features:

                properties = feature["properties"]
                coordinates = feature["geometry"]["coordinates"]

                record = {
                    "id": feature["id"],
                    "time": properties["time"],
                    "updated": properties["updated"],
                    "latitude": coordinates[1],
                    "longitude": coordinates[0],
                    "depth_km": coordinates[2],
                    "mag": properties["mag"],
                    "magType": properties["magType"],
                    "place": properties["place"],
                    "status": properties["status"],
                    "tsunami": properties["tsunami"],
                    "sig": properties["sig"],
                    "net": properties["net"],
                    "nst": properties["nst"],
                    "dmin": properties["dmin"],
                    "rms": properties["rms"],
                    "gap": properties["gap"],
                    "magError": properties.get("magError"),
                    "depthError": properties.get("depthError"),
                    "magNst": properties.get("magNst"),
                    "types": properties.get("types"),
                    "ids": properties["ids"],
                    "sources": properties["sources"],
                    "type": properties["type"]
                }

                # Add dictionary to list
                all_records.append(record)

        else:
            print("API Error:", response.status_code)

# Convert list of dictionaries to DataFrame
df = pd.DataFrame(all_records)

print("\nTotal records:", len(df))
print(df.head())
print(df.shape)

Extracting: 2021-01-01 → 2021-02-01
Earthquakes found: 1714
Extracting: 2021-02-01 → 2021-03-01
Earthquakes found: 1815
Extracting: 2021-03-01 → 2021-04-01
Earthquakes found: 2437
Extracting: 2021-04-01 → 2021-05-01
Earthquakes found: 1577
Extracting: 2021-05-01 → 2021-06-01
Earthquakes found: 1604
Extracting: 2021-06-01 → 2021-07-01
Earthquakes found: 1613
Extracting: 2021-07-01 → 2021-08-01
Earthquakes found: 1801
Extracting: 2021-08-01 → 2021-09-01
Earthquakes found: 2683
Extracting: 2021-09-01 → 2021-10-01
Earthquakes found: 1688
Extracting: 2021-10-01 → 2021-11-01
Earthquakes found: 1536
Extracting: 2021-11-01 → 2021-12-01
Earthquakes found: 1543
Extracting: 2021-12-01 → 2022-01-01
Earthquakes found: 1915
Extracting: 2022-01-01 → 2022-02-01
Earthquakes found: 1910
Extracting: 2022-02-01 → 2022-03-01
Earthquakes found: 1615
Extracting: 2022-03-01 → 2022-04-01
Earthquakes found: 1917
Extracting: 2022-04-01 → 2022-05-01
Earthquakes found: 1657
Extracting: 2022-05-01 → 2022-06-01
Earthquakes found: 1507
Extracting: 2022-06-01 → 2022-07-01
Earthquakes found: 1530
Extracting: 2022-07-01 → 2022-08-01
Earthquakes found: 1693
Extracting: 2022-08-01 → 2022-09-01
Earthquakes found: 1681
Extracting: 2022-09-01 → 2022-10-01
Earthquakes found: 1903
Extracting: 2022-10-01 → 2022-11-01
Earthquakes found: 1618
Extracting: 2022-11-01 → 2022-12-01
Earthquakes found: 1644
Extracting: 2022-12-01 → 2023-01-01
Earthquakes found: 1533
Extracting: 2023-01-01 → 2023-02-01
Earthquakes found: 1787
Extracting: 2023-02-01 → 2023-03-01
Earthquakes found: 1852
Extracting: 2023-03-01 → 2023-04-01
Earthquakes found: 1634
Extracting: 2023-04-01 → 2023-05-01
Earthquakes found: 1548
Extracting: 2023-05-01 → 2023-06-01
Earthquakes found: 1851
Extracting: 2023-06-01 → 2023-07-01
Earthquakes found: 1644
Extracting: 2023-07-01 → 2023-08-01
Earthquakes found: 1559
Extracting: 2023-08-01 → 2023-09-01
Earthquakes found: 1498
Extracting: 2023-09-01 → 2023-10-01
Earthquakes found: 1453
Extracting: 2023-10-01 → 2023-11-01
Earthquakes found: 1738
Extracting: 2023-11-01 → 2023-12-01
Earthquakes found: 1752
Extracting: 2023-12-01 → 2024-01-01
Earthquakes found: 2514
Extracting: 2024-01-01 → 2024-02-01
Earthquakes found: 1734
Extracting: 2024-02-01 → 2024-03-01
Earthquakes found: 1529
Extracting: 2024-03-01 → 2024-04-01
Earthquakes found: 1446
Extracting: 2024-04-01 → 2024-05-01
Earthquakes found: 1841
Extracting: 2024-05-01 → 2024-06-01
Earthquakes found: 1608
Extracting: 2024-06-01 → 2024-07-01
Earthquakes found: 1435
Extracting: 2024-07-01 → 2024-08-01
Earthquakes found: 1444
Extracting: 2024-08-01 → 2024-09-01
Earthquakes found: 1426
Extracting: 2024-09-01 → 2024-10-01
Earthquakes found: 1386
Extracting: 2024-10-01 → 2024-11-01
Earthquakes found: 1525
Extracting: 2024-11-01 → 2024-12-01
Earthquakes found: 1437
Extracting: 2024-12-01 → 2025-01-01
Earthquakes found: 1848
Extracting: 2025-01-01 → 2025-02-01
Earthquakes found: 1745
Extracting: 2025-02-01 → 2025-03-01
Earthquakes found: 1712
Extracting: 2025-03-01 → 2025-04-01
Earthquakes found: 1634
Extracting: 2025-04-01 → 2025-05-01
Earthquakes found: 1688
Extracting: 2025-05-01 → 2025-06-01
Earthquakes found: 1586
Extracting: 2025-06-01 → 2025-07-01
Earthquakes found: 1499
Extracting: 2025-07-01 → 2025-08-01
Earthquakes found: 3328
Extracting: 2025-08-01 → 2025-09-01
Earthquakes found: 2569
Extracting: 2025-09-01 → 2025-10-01
Earthquakes found: 1892
Extracting: 2025-10-01 → 2025-11-01
Earthquakes found: 1728
Extracting: 2025-11-01 → 2025-12-01
Earthquakes found: 1578
Extracting: 2025-12-01 → 2026-01-01
Earthquakes found: 1865
Extracting: 2026-01-01 → 2026-02-01
Earthquakes found: 1688
Extracting: 2026-02-01 → 2026-03-01
Earthquakes found: 1542
Extracting: 2026-03-01 → 2026-04-01
Earthquakes found: 1860
Extracting: 2026-04-01 → 2026-05-01
Earthquakes found: 2021
Extracting: 2026-05-01 → 2026-06-01
Earthquakes found: 1606
Extracting: 2026-06-01 → 2026-07-01
Earthquakes found: 1876
Extracting: 2026-07-01 → 2026-08-01
Earthquakes found: 2011
Extracting: 2026-08-01 → 2026-09-01
Earthquakes found: 1969
Extracting: 2026-09-01 → 2026-10-01
Earthquakes found: 1179
Extracting: 2026-10-01 → 2026-11-01
Earthquakes found: 0
Extracting: 2026-11-01 → 2026-12-01
Earthquakes found: 0
Extracting: 2026-12-01 → 2027-01-01
Earthquakes found: 0

Total records: 120199
           id           time        updated  latitude  longitude  depth_km  \
0  us6000ddi8  1612135249923  1618599764040  -31.7493   -68.9337     17.27
1  us6000dev6  1612134497161  1618599827040  -15.4902  -177.2052    426.71
2  us6000dev5  1612133659760  1618599827040   19.7529   121.3159     46.73
3  us6000ddhs  1612130760832  1618599763040   28.1524    57.2570     10.00
4  us6000dev4  1612129874016  1618599826040   71.3212    -3.7578     10.00

   mag magType                                              place    status  \
0  4.7     mwr        29 km SW of Villa Basilio Nievas, Argentina  reviewed
1  4.1      mb                                        Fiji region  reviewed
2  4.7      mb                    103 km SW of Basco, Philippines  reviewed
3  4.9      mb                            114 km N of M?n?b, Iran  reviewed
4  4.0      mb  184 km ENE of Olonkinbyen, Svalbard and Jan Mayen  reviewed

   ...   dmin   rms    gap  magError  depthError  magNst  \
0  ...  0.294  0.82   42.0      None        None    None
1  ...  1.471  0.29   64.0      None        None    None
2  ...  3.057  0.69  106.0      None        None    None
3  ...  3.330  0.61   71.0      None        None    None
4  ...  6.023  0.50   65.0      None        None    None

                                    types           ids sources        type
0  ,dyfi,moment-tensor,origin,phase-data,  ,us6000ddi8,    ,us,  earthquake
1                     ,origin,phase-data,  ,us6000dev6,    ,us,  earthquake
2                     ,origin,phase-data,  ,us6000dev5,    ,us,  earthquake
3                     ,origin,phase-data,  ,us6000ddhs,    ,us,  earthquake
4                     ,origin,phase-data,  ,us6000dev4,    ,us,  earthquake

[5 rows x 24 columns]
(120199, 24)

In [ ]:
# R&C after extracted (120199, 24):
df.shape

(120199, 24)

In [9]:
df["time"] = pd.to_datetime(df["time"], unit="ms")

## Save df to CSV file:

In [10]:
import os

In [23]:
df["time"] = pd.to_datetime(df["time"], errors="coerce")

#df["time"] = df["time"].dt.strftime("%Y-%m-%d %H:%M:%S")

df.to_csv(
    r"D:\DS Course\Earthquake_P1\earthquake_rec_data1.csv",
    index=False,
    encoding="utf-8"
)

print("CSV saved successfully")

CSV saved successfully

# Data Inspection:

In [24]:
df.head(3)

,id,time,updated,latitude,longitude,depth_km,mag,magType,place,status,...,sig,net,nst,dmin,rms,gap,types,ids,sources,type
0,us6000ddi8,2021-01-31 23:20:49,1970-01-01 00:26:58.599764040,-31.7493,-68.9337,17.27,4.7,mwr,"29 km SW of Villa Basilio Nievas, Argentina",reviewed,...,344,us,11.0,0.294,0.82,42.0,",dyfi,moment-tensor,origin,phase-data,",",us6000ddi8,",",us,",earthquake
1,us6000dev6,2021-01-31 23:08:17,1970-01-01 00:26:58.599827040,-15.4902,-177.2052,426.71,4.1,mb,Fiji region,reviewed,...,259,us,11.0,1.471,0.29,64.0,",origin,phase-data,",",us6000dev6,",",us,",earthquake
2,us6000dev5,2021-01-31 22:54:19,1970-01-01 00:26:58.599827040,19.7529,121.3159,46.73,4.7,mb,"103 km SW of Basco, Philippines",reviewed,...,340,us,11.0,3.057,0.69,106.0,",origin,phase-data,",",us6000dev5,",",us,",earthquake

In [25]:
#While saving to csv (120199, 24) by sep 28: before it is 120134
df.shape

(120199, 21)

In [26]:
df.columns

Index(['id', 'time', 'updated', 'latitude', 'longitude', 'depth_km', 'mag',
       'magType', 'place', 'status', 'tsunami', 'sig', 'net', 'nst', 'dmin',
       'rms', 'gap', 'types', 'ids', 'sources', 'type'],
      dtype='str')

In [27]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 120199 entries, 0 to 120198
Data columns (total 21 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   id         120199 non-null  str
 1   time       120199 non-null  datetime64[us]
 2   updated    120199 non-null  datetime64[ns]
 3   latitude   120199 non-null  float64
 4   longitude  120199 non-null  float64
 5   depth_km   120199 non-null  float64
 6   mag        120199 non-null  float64
 7   magType    120199 non-null  str
 8   place      120199 non-null  str
 9   status     120199 non-null  str
 10  tsunami    120199 non-null  int64
 11  sig        120199 non-null  int64
 12  net        120199 non-null  str
 13  nst        120199 non-null  float64
 14  dmin       120199 non-null  float64
 15  rms        120199 non-null  float64
 16  gap        120199 non-null  float64
 17  types      120199 non-null  str
 18  ids        120199 non-null  str
 19  sources    120199 non-null  str
 20  type       120199 non-null  str
dtypes: datetime64[ns](1), datetime64[us](1), float64(8), int64(2), str(9)
memory usage: 31.6 MB

In [28]:
# Data Cleaning:
# Find NULL Values:
df.isna().sum()

id           0
time         0
updated      0
latitude     0
longitude    0
depth_km     0
mag          0
magType      0
place        0
status       0
tsunami      0
sig          0
net          0
nst          0
dmin         0
rms          0
gap          0
types        0
ids          0
sources      0
type         0
dtype: int64

In [ ]:
# Drop the columns magError, depthError,magNst
df = df.drop(
    ["magError", "depthError", "magNst"],
    axis=1
)

In [31]:
df.isna().sum()

id           0
time         0
updated      0
latitude     0
longitude    0
depth_km     0
mag          0
magType      0
place        0
status       0
tsunami      0
sig          0
net          0
nst          0
dmin         0
rms          0
gap          0
types        0
ids          0
sources      0
type         0
dtype: int64

In [32]:
# Handling NULL Values using ffill and bfill:

cols = ["nst", "rms", "dmin", "gap"]

df[cols] = df[cols].bfill()

In [33]:
df.isna().sum()

id           0
time         0
updated      0
latitude     0
longitude    0
depth_km     0
mag          0
magType      0
place        0
status       0
tsunami      0
sig          0
net          0
nst          0
dmin         0
rms          0
gap          0
types        0
ids          0
sources      0
type         0
dtype: int64

# Cleaning datetime Fields:

In [21]:
df.columns

Index(['id', 'time', 'updated', 'latitude', 'longitude', 'depth_km', 'mag',
       'magType', 'place', 'status', 'tsunami', 'sig', 'net', 'nst', 'dmin',
       'rms', 'gap', 'types', 'ids', 'sources', 'type'],
      dtype='str')

In [34]:
# 1. TIME FIELD:
# Already time field is cleared but not updated time:

df["time"]=pd.to_datetime(df["time"],errors="coerce")  # to convert ms to datetime format
df["updated"] = pd.to_datetime(df["updated"], errors="coerce")

#df["updated"] = df["updated"].dt.strftime("%Y-%m-%d %H:%M:%S") # to convert the datetime to string format

In [37]:
df[['time','updated']].dtypes

time       datetime64[us]
updated    datetime64[ns]
dtype: object

In [36]:
# To derive Year, Month , Day & Day of week from dataset:
df["time"] = pd.to_datetime(df["time"], errors="coerce")

df["year"] = df["time"].dt.year
df["month"]=df["time"].dt.month
df["day_of_week"]=df["time"].dt.day_of_week

In [83]:
df["event_date"]=df["time"].dt.date
df["event_time"]=df["time"].dt.time

In [38]:
#2. TEXT FIELD:
# Clear the text field using regular expression
#country = re.findall(r'[^,]+$', place)[0].strip()
import re
df["Country"] = df["place"].str.extract(r'([^,]+)$').iloc[:, 0].str.strip()

In [39]:
# to normalize the column:

df["sources"] = df["sources"].str.replace(r"^,|,$", "", regex=True)
df["types"] = df["types"].str.replace(r"^,|,$", "", regex=True)
df["ids"] = df["ids"].str.replace(r"^,|,$", "", regex=True)

# To drop the column "ids" as "ID" and "IDS" are same:
df=df.drop(["ids"], axis=1)
df["id"]=df["id"].str.upper()

In [ ]:
#  EXTRACT DISTANCE_KM FROM PLACE:

df["distance_km"]=df["place"].str.extract(r"^(\d+)")[0].astype("Int64")

In [72]:
# Fill null values with "0" in distance_km:
df["distance_km"]=df["distance_km"].fillna(0)

In [40]:
df.value_counts(["status","magType","type","net","sources","types"])

status    magType  type        net  sources   types
reviewed  mb       earthquake  us   us        origin,phase-data                                                          72415
          ml       earthquake  us   ak,us     origin,phase-data                                                           6661
          mb       earthquake  us   us        dyfi,origin,phase-data                                                      5724
          md       earthquake  pr   us,pr     origin,phase-data                                                           2785
                                    pr        origin,phase-data                                                           2366
                                                                                                                         ...
          mww      earthquake  us   at,us     dyfi,event-sequence,impact-link,moment-tensor,oaf,origin,phase-data            1
          ml       earthquake  uw   ew,uw,us  dyfi,moment-tensor,origin,phase-data,shake-alert,shakemap                      1
          mww      earthquake  us   us,at,ak  event-sequence,impact-link,moment-tensor,oaf,origin,phase-data,shakemap        1
                                    us,ak     event-sequence,losspager,moment-tensor,oaf,origin,phase-data,shakemap          1
                                    us        ground-failure,impact-text,losspager,origin,phase-data,shakemap                1
Name: count, Length: 2032, dtype: int64

In [41]:
# 3.Derived Columns for depth_km & mag:

# To find shallow or depth earthquake using DEPTH_KM:


cond=[
       (df.depth_km <=70.00),
       (df.depth_km>70.00)&(df.depth_km<=300.00),
       (df.depth_km>300.00)&(df.depth_km<=700.00)
    ]
df["depth_cat"]=np.select(cond,["Shallow","Intermediate","Deep"],
       default="unknown")

In [42]:
# To find the strength of earthquake using magnitude: (3 to 8)

condition=[
       (df.mag <=3.9),
       (df.mag>=4.0)&(df.mag<=4.9),
       (df.mag>=5.0)&(df.mag<=5.9),
       (df.mag>=6.0)&(df.mag<=6.9),
       (df.mag>=7.0)&(df.mag<=7.9),
       (df.mag>=8.0)
    ]
df["mag_cat"]=np.select(condition,["Minor","Light","Moderate","Strong","Major","Great"],
       default="unknown")

# Continent Country Conversion:

In [ ]:
#SAMPLE EXAMPLE
#print(pc.country_name_to_country_alpha2("India"))

IN

In [43]:
def get_continent(country):
    try:
        country_code = pc.country_name_to_country_alpha2(country)
        continent_code = pc.country_alpha2_to_continent_code(country_code)
        return pc.convert_continent_code_to_continent_name(continent_code)
    except:
        return "Unknown"

df["Continent"] = df["Country"].apply(get_continent)

In [44]:
df[['Continent','Country']].head()

       Continent                 Country
0  South America               Argentina
1        Unknown             Fiji region
2           Asia             Philippines
3           Asia                    Iran
4         Europe  Svalbard and Jan Mayen

In [74]:
df.head(5)

,id,time,updated,latitude,longitude,depth_km,mag,magType,place,status,...,sources,type,year,month,day_of_week,Country,depth_cat,mag_cat,Continent,distance_km
0,US6000DDI8,2021-01-31 23:20:49,1970-01-01 00:26:58.599764040,-31.7493,-68.9337,17.27,4.7,mwr,"29 km SW of Villa Basilio Nievas, Argentina",reviewed,...,us,earthquake,2021,1,6,Argentina,Shallow,Light,South America,29
1,US6000DEV6,2021-01-31 23:08:17,1970-01-01 00:26:58.599827040,-15.4902,-177.2052,426.71,4.1,mb,Fiji region,reviewed,...,us,earthquake,2021,1,6,Fiji region,Deep,Light,Unknown,0
2,US6000DEV5,2021-01-31 22:54:19,1970-01-01 00:26:58.599827040,19.7529,121.3159,46.73,4.7,mb,"103 km SW of Basco, Philippines",reviewed,...,us,earthquake,2021,1,6,Philippines,Shallow,Light,Asia,103
3,US6000DDHS,2021-01-31 22:06:00,1970-01-01 00:26:58.599763040,28.1524,57.2570,10.00,4.9,mb,"114 km N of M?n?b, Iran",reviewed,...,us,earthquake,2021,1,6,Iran,Shallow,Light,Asia,114
4,US6000DEV4,2021-01-31 21:51:14,1970-01-01 00:26:58.599826040,71.3212,-3.7578,10.00,4.0,mb,"184 km ENE of Olonkinbyen, Svalbard and Jan Mayen",reviewed,...,us,earthquake,2021,1,6,Svalbard and Jan Mayen,Shallow,Light,Europe,184

In [75]:
#Final cleaned data (120199, 27):
df.shape

(120199, 28)

# Saving cleaned data:

In [85]:
df.to_csv(
    r"D:\DS Course\Earthquake_P1\earthquake_clean_data.csv",
    index=False,
    encoding="utf-8"
)

print("Cleaned CSV saved successfully")

Cleaned CSV saved successfully

In [50]:
df.shape
print(len(df))

120199

In [77]:
df = df.drop_duplicates()

In [52]:
df.shape

(120199, 27)

In [87]:
df.to_csv(
    r"D:\DS Course\Earthquake_P1\earthquake_clean_data1.csv",
    index=False
)
print("CSV:", len(df))

CSV: 120199

In [80]:
df.dtypes

id                        str
time           datetime64[us]
updated        datetime64[ns]
latitude              float64
longitude             float64
depth_km              float64
mag                   float64
magType                   str
place                     str
status                    str
tsunami                 int64
sig                     int64
net                       str
nst                     int32
dmin                  float64
rms                   float64
gap                   float64
types                     str
sources                   str
type                      str
year                    int32
month                   int32
day_of_week             int32
Country                   str
depth_cat                 str
mag_cat                   str
Continent                 str
distance_km             Int64
dtype: object

In [81]:
# NST is in float change to int:
df["nst"]=df["nst"].astype('int32')
df["nst"].dtypes

dtype('int32')

In [59]:
df.columns

Index(['id', 'time', 'updated', 'latitude', 'longitude', 'depth_km', 'mag',
       'magType', 'place', 'status', 'tsunami', 'sig', 'net', 'nst', 'dmin',
       'rms', 'gap', 'types', 'sources', 'type', 'year', 'month',
       'day_of_week', 'Country', 'depth_cat', 'mag_cat', 'Continent'],
      dtype='str')

In [60]:
df[["type","tsunami"]].value_counts()

type                    tsunami
earthquake              0          118629
mining explosion        0             854
earthquake              1             669
ice quake               0              13
volcanic eruption       0              11
experimental explosion  0               5
landslide               0               5
other event             0               5
mine collapse           0               3
quarry blast            0               2
volcanic eruption       1               1
Landslide               0               1
explosion               0               1
Name: count, dtype: int64

In [61]:
total_unique_nst = df["nst"].nunique()

print("Total unique NST values:", total_unique_nst)

Total unique NST values: 360

In [64]:
# TIME FIELD CHECKING:
print(df["time"].head())
print(df["time"].dtype)
df['nst'].dtypes

0   2021-01-31 23:20:49
1   2021-01-31 23:08:17
2   2021-01-31 22:54:19
3   2021-01-31 22:06:00
4   2021-01-31 21:51:14
Name: time, dtype: datetime64[us]
datetime64[us]

dtype('int32')

In [82]:
df.head()

,id,time,updated,latitude,longitude,depth_km,mag,magType,place,status,...,sources,type,year,month,day_of_week,Country,depth_cat,mag_cat,Continent,distance_km
0,US6000DDI8,2021-01-31 23:20:49,1970-01-01 00:26:58.599764040,-31.7493,-68.9337,17.27,4.7,mwr,"29 km SW of Villa Basilio Nievas, Argentina",reviewed,...,us,earthquake,2021,1,6,Argentina,Shallow,Light,South America,29
1,US6000DEV6,2021-01-31 23:08:17,1970-01-01 00:26:58.599827040,-15.4902,-177.2052,426.71,4.1,mb,Fiji region,reviewed,...,us,earthquake,2021,1,6,Fiji region,Deep,Light,Unknown,0
2,US6000DEV5,2021-01-31 22:54:19,1970-01-01 00:26:58.599827040,19.7529,121.3159,46.73,4.7,mb,"103 km SW of Basco, Philippines",reviewed,...,us,earthquake,2021,1,6,Philippines,Shallow,Light,Asia,103
3,US6000DDHS,2021-01-31 22:06:00,1970-01-01 00:26:58.599763040,28.1524,57.2570,10.00,4.9,mb,"114 km N of M?n?b, Iran",reviewed,...,us,earthquake,2021,1,6,Iran,Shallow,Light,Asia,114
4,US6000DEV4,2021-01-31 21:51:14,1970-01-01 00:26:58.599826040,71.3212,-3.7578,10.00,4.0,mb,"184 km ENE of Olonkinbyen, Svalbard and Jan Mayen",reviewed,...,us,earthquake,2021,1,6,Svalbard and Jan Mayen,Shallow,Light,Europe,184